Fix all encrypt/decrypt/encryption scripts that take a path to ensure it's not an absolute path before trying to use it...

diff --git a/src/scripts/encryption/kaptain-encrypt b/src/scripts/encryption/kaptain-encrypt
--- a/src/scripts/encryption/kaptain-encrypt
+++ b/src/scripts/encryption/kaptain-encrypt
@@ -64,6 +64,12 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
+# Reject absolute paths
+if [[ "${DIR}" == /* ]]; then
+  echo "ERROR: --dir must be a relative path, i.e. a sub path of this repo" >&2
+  exit 1
+fi
+
 if [[ ! -d "${DIR}" ]]; then
   echo "ERROR: Directory not found: ${DIR}" >&2
   exit 1
diff --git a/src/scripts/encryption/kaptain-encryption-check-ignores b/src/scripts/encryption/kaptain-encryption-check-ignores
--- a/src/scripts/encryption/kaptain-encryption-check-ignores
+++ b/src/scripts/encryption/kaptain-encryption-check-ignores
@@ -28,6 +28,12 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
+# Reject absolute paths
+if [[ "${SECRETS_DIR}" == /* ]]; then
+  echo "ERROR: --dir must be a relative path, i.e. a sub path of this repo" >&2
+  exit 1
+fi
+
 # Secrets dir must exist
 if [[ ! -d "${SECRETS_DIR}" ]]; then
   echo "ERROR: Secrets dir ${SECRETS_DIR}/ does not exist." >&2
